name: hotel_booking
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  shimmer: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  salomon_bottom_bar: ^3.3.1
  cached_network_image: ^3.2.3
  image_network: ^2.5.1
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.1.3
  http: ^0.13.5
  url_launcher: ^6.1.10
  connectivity_plus: ^3.0.3
  flutter_svg: ^1.1.1
  concentric_transition: ^1.0.3
  card_swiper: ^2.0.4
  image_picker: ^0.8.7+1
  cookie_jar: ^4.0.1
  map_launcher: ^2.2.3
  geocoder:
    git: https://github.com/aloisdeniel/flutter_geocoder.git
  geolocator: ^9.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/logo/
